site_name: 'Interview ğŸ’'
site_url: https://interview.jaronnie.github.io
repo_url: https://github.com/jaronnie/interview
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs
  palette:
    primary: light blue

nav:
  - index.md
  - å…¬å¸.md

plugins:
  - search
  - redirects:
      redirect_maps:
        'repo.md':      'https://github.com/jaronnie/interview'
        'issues.md':    'https://github.com/jaronnie/interview/issues'
        'prs.md':       'https://github.com/jaronnie/interview/pulls'
        'releases.md':  'https://github.com/jaronnie/interview/releases'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences