site_name: 'Interview ğŸ’'
site_url: https://interview.jaronnie.github.io
repo_url: https://github.com/jaronnie/interview
edit_uri: edit/main/docs/

theme:
  name: material
  logo: https://oss.jaronnie.com/avatar.png
  favicon: https://oss.jaronnie.com/avatar.png
  custom_dir: docs
  palette:
    primary: light blue

nav:
  - index.md
  - company.md
  - HR:
    - hr/index.md
  - Golang:
    - golang/questions-from-others.md
    - golang/questions-from-myself.md
  - æ•°æ®åº“:
    - db/redis.md
  - å®¹å™¨:
    - container/docker.md
  - ç½‘ç»œ:
    - network/tcp.md

plugins:
  - search
  - redirects:
      redirect_maps:
        'repo.md':      'https://github.com/jaronnie/interview'
        'issues.md':    'https://github.com/jaronnie/interview/issues'
        'prs.md':       'https://github.com/jaronnie/interview/pulls'
        'releases.md':  'https://github.com/jaronnie/interview/releases'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences